// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBattler.DAL;

#nullable disable

namespace WebBattler.DAL.Migrations
{
    [DbContext(typeof(AutobattlerDbContext))]
    [Migration("20260218100842_Production-Fix")]
    partial class ProductionFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvinceEntityProvinceEntity", b =>
                {
                    b.Property<int>("NeighboursId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceEntityId")
                        .HasColumnType("int");

                    b.HasKey("NeighboursId", "ProvinceEntityId");

                    b.HasIndex("ProvinceEntityId");

                    b.ToTable("ProvinceNeighbours", (string)null);
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.ArmyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentTurnCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Armies");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.BuildingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Profit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.BuildingSampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildTurns")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Profit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("BuildingSamples");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCapital")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.CountryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.GameSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentTurn")
                        .HasColumnType("int");

                    b.Property<int>("CurrentYear")
                        .HasColumnType("int");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId")
                        .IsUnique();

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.ProductionOrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArmyId")
                        .HasColumnType("int");

                    b.Property<int?>("BuildingSampleId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReadyTurn")
                        .HasColumnType("int");

                    b.Property<int>("StartTurn")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UnitSampleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.HasIndex("BuildingSampleId");

                    b.HasIndex("CityId");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("UnitSampleId");

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.ProvinceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("ProvinceEntity");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.UnitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmyId")
                        .HasColumnType("int");

                    b.Property<float>("Health")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Weapon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArmyId");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.UnitSampleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildTurns")
                        .HasColumnType("int");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<float>("Health")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OwnerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Weapon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("UnitSamples");
                });

            modelBuilder.Entity("ProvinceEntityProvinceEntity", b =>
                {
                    b.HasOne("WebBattler.DAL.Entities.ProvinceEntity", null)
                        .WithMany()
                        .HasForeignKey("NeighboursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBattler.DAL.Entities.ProvinceEntity", null)
                        .WithMany()
                        .HasForeignKey("ProvinceEntityId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.ArmyEntity", b =>
                {
                    b.HasOne("WebBattler.DAL.Entities.CityEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WebBattler.DAL.Entities.CountryEntity", "Country")
                        .WithMany("Armies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBattler.DAL.Entities.ArmyEntity", "Parent")
                        .WithMany("SubArmies")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("WebBattler.DAL.Entities.ProvinceEntity", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("Parent");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.BuildingEntity", b =>
                {
                    b.HasOne("WebBattler.DAL.Entities.CityEntity", "City")
                        .WithMany("Buildings")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.BuildingSampleEntity", b =>
                {
                    b.HasOne("WebBattler.DAL.Entities.CountryEntity", "Country")
                        .WithMany("BuildingSamples")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.CityEntity", b =>
                {
                    b.HasOne("WebBattler.DAL.Entities.ProvinceEntity", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.CountryEntity", b =>
                {
                    b.HasOne("WebBattler.DAL.Entities.GameSessionEntity", "GameSession")
                        .WithMany("Countries")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.ProductionOrderEntity", b =>
                {
                    b.HasOne("WebBattler.DAL.Entities.ArmyEntity", "Army")
                        .WithMany()
                        .HasForeignKey("ArmyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebBattler.DAL.Entities.BuildingSampleEntity", "BuildingSample")
                        .WithMany()
                        .HasForeignKey("BuildingSampleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebBattler.DAL.Entities.CityEntity", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebBattler.DAL.Entities.GameSessionEntity", "GameSession")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBattler.DAL.Entities.UnitSampleEntity", "UnitSample")
                        .WithMany()
                        .HasForeignKey("UnitSampleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Army");

                    b.Navigation("BuildingSample");

                    b.Navigation("City");

                    b.Navigation("GameSession");

                    b.Navigation("UnitSample");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.ProvinceEntity", b =>
                {
                    b.HasOne("WebBattler.DAL.Entities.CountryEntity", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.UnitEntity", b =>
                {
                    b.HasOne("WebBattler.DAL.Entities.ArmyEntity", "Army")
                        .WithMany("Units")
                        .HasForeignKey("ArmyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Army");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.UnitSampleEntity", b =>
                {
                    b.HasOne("WebBattler.DAL.Entities.CountryEntity", "Country")
                        .WithMany("UnitSamples")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.ArmyEntity", b =>
                {
                    b.Navigation("SubArmies");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.CityEntity", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.CountryEntity", b =>
                {
                    b.Navigation("Armies");

                    b.Navigation("BuildingSamples");

                    b.Navigation("Provinces");

                    b.Navigation("UnitSamples");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.GameSessionEntity", b =>
                {
                    b.Navigation("Countries");

                    b.Navigation("ProductionOrders");
                });

            modelBuilder.Entity("WebBattler.DAL.Entities.ProvinceEntity", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
